[package]
name = "advent22"
auhor = "Edvard All"
version = "0.1.0"
edition = "2021"
about = "Simple CLI app for advent of code."

[dependencies]
anyhow = "1.0.66"
itertools = "0.10.5"
numerals = "0.1"
clap = {version = "4.0.29", features = ["unicode", "derive"]}
chrono = "0.4.23"
